### ISSUE TITLE
App.js

### ISSUE THREAD

**Issue by jema28** [FACN4/week8-wdgaf#64]
Great structure and use of express-session 💯 

Few issues:
- Unused morgan module
- Noticed you destructured SECRET but didn't use it:
<img width="378" alt="screen shot 2018-08-24 at 14 12 31" src="https://user-images.githubusercontent.com/25960351/44581795-dfbeca80-a7a7-11e8-8310-245f32e80f0d.png">

**Comment by matthall8** [comment]
This is fixed in the latest commit. Please can you have a look and close if you agree.
