### ISSUE TITLE
Unused modules in login controller

### ISSUE THREAD

**Issue by jema28** [FACN4/week8-wdgaf#65]
I'd watch out for unused imports as they slow down your app (querystring, cookie, jsonwebtoken in this file).

<img width="435" alt="screen shot 2018-08-24 at 14 18 01" src="https://user-images.githubusercontent.com/25960351/44582034-bfdbd680-a7a8-11e8-9dad-75ed5e027456.png">

**Comment by afifisuha** [comment]
now fixed could please check and close
